# Generated by Django 3.2.18 on 2023-08-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField(default='')),
                ('img', models.ImageField(upload_to='Scholarships')),
                ('type', models.BooleanField(default=True)),
                ('num_of_disks', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('details', models.TextField()),
                ('summary', models.TextField()),
                ('stage', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('deadline', models.DateField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField()),
                ('country', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(upload_to='students_profiles')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='University')),
                ('url', models.URLField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.FileField(upload_to='Order_degree')),
                ('identification', models.FileField(upload_to='Order_identification')),
                ('passport', models.FileField(upload_to='Order_passport')),
                ('money_transaction_num', models.IntegerField(null=True)),
                ('state', models.IntegerField(default=0)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mysite.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mysite.student')),
            ],
        ),
    ]
