# Generated by Django 3.2.18 on 2023-08-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='rate',
        ),
    ]
