# Generated by Django 4.2.7 on 2023-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0004_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='identification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='money_transaction_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='passport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='img',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.CharField(max_length=50),
        ),
    ]
