# Generated by Django 4.2.7 on 2023-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0005_alter_order_degree_alter_order_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
