# Generated by Django 4.2.7 on 2023-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0006_alter_student_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('fallName', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
    ]
