# Generated by Django 4.2.7 on 2023-12-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0009_rate_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='student',
        ),
        migrations.CreateModel(
            name='Std_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mysite.scholarship')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mysite.student')),
            ],
        ),
    ]
